# version: 1.0.0
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
continuation_prompt = "[▸▹ ](dimmed white)"

format = """($nix_shell$container$fill$git_metrics\n)$cmd_duration\
$username\
$hostname\
$localip\
$shlvl\
$shell\
$env_var\
$jobs\
$character"""

right_format = """
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cpp\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$fortran\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$xmake\
$zig\
$buf\
$conda\
$pixi\
$meson\
$spack\
$memory_usage\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$status\
$os\
$time"""

[fill]
symbol = ' '

[character]
format = "$symbol "
success_symbol = "[⭘](bold italic bright-green)"
error_symbol = "[⭘](bold italic bright-red)"
vimcmd_symbol = "[■](italic dimmed green)"
# not supported in zsh
vimcmd_replace_one_symbol = "◌"
vimcmd_replace_symbol = "□"
vimcmd_visual_symbol = "▼"

[env_var.VIMSHELL]
format = "[$env_value](green italic)"

[sudo]
disabled = false
format = "[$symbol](bold italic bright-purple)"
symbol = "sudo "

[username]
disabled = false
show_always = true
format = "[$user](bright-red bold italic)"

[hostname]
disabled = false
ssh_only = false
format = "[@$hostname](bright-yellow bold italic) "
ssh_symbol = " "

[directory]
# home_symbol = ""
home_symbol = "HOME"
truncation_length = 2
truncate_to_repo = false
truncation_symbol = "../"
read_only = " 󰌾"
use_os_path_sep = true
style = "italic blue"
format = '[$path]($style)[$read_only]($read_only_style) '

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[cmd_duration]
format = "[command lasted $duration ](italic white)"

[jobs]
format = "[$symbol$number]($style) "
style = "white"
symbol = "[▶](blue italic)"

[localip]
disabled = false
ssh_only = true
format = " [on $localipv4](bold magenta) "

[time]
disabled = false
format = "[ $time](italic dimmed white)"
time_format = "%R"
utc_time_offset = "local"

[battery]
format = " [$symbol$percentage]($style) "

[[battery.display]]
threshold = 20
style = "italic bold red"

[[battery.display]]
threshold = 60
style = "italic dimmed bright-purple"

[[battery.display]]
threshold = 70
style = "italic dimmed yellow"

[git_branch]
#format = " [$branch(:$remote_branch)]($style)"
#symbol = "[@](bold italic bright-blue)"
#style = "italic bright-blue"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'
symbol = ""
style = "bg:#394260"
truncation_symbol = "⋯"
truncation_length = 11
ignore_branches = ["main", "master"]
only_attached = true

[git_metrics]
format = '([+$added]($added_style))([-$deleted]($deleted_style))'
added_style = 'italic dimmed green'
deleted_style = 'italic dimmed red'
ignore_submodules = true
disabled = false

[git_status]
style = "bold italic bright-blue"
format = "([ $ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed]($style))"
conflicted = "[conflicted ${count}](italic bright-magenta) "
ahead = "[ahead ${count}](italic green) "
behind = "[behind ${count}](italic red) "
diverged = "[diverged ${ahead_count} ↓${behind_count}](italic bright-magenta) "
untracked = "[untracked ${count}](italic bright-yellow) "
stashed = "[stashed](italic white) "
modified = "[modified ${count}](italic yellow) "
staged = "[staged ${count}](italic bright-cyan) "
renamed = "[renamed ${count}](italic bright-blue) "
deleted = "[deleted ${count}](italic red) "

[bun]
format = "via [$symbol]($style)"

[buf]
format = "with [$symbol]($style)"

[c]
format = "via [$symbol($name)]($style)"

[cmake]
format = "via [$symbol]($style)"

[cobol]
format = "via [$symbol]($style)"

[cpp]
format = "via [$symbol($name)]($style)"

[crystal]
format = "via [$symbol]($style)"

[daml]
format = "via [$symbol]($style)"

[dart]
format = "via [$symbol]($style)"

[deno]
format = "via [$symbol]($style)"

[dotnet]
format = "[$symbol(🎯 $tfm )]($style)"

[elixir]
format = 'via [$symbol]($style)'

[elm]
format = 'via [$symbol]($style)'

[erlang]
format = 'via [$symbol]($style)'

[fennel]
format = 'via [$symbol]($style)'

[fortran]
format = 'via [$symbol]($style)'

[gleam]
format = 'via [$symbol]($style)'

[golang]
format = 'via [$symbol]($style)'

[gradle]
format = 'via [$symbol]($style)'

[haskell]
format = 'via [$symbol]($style)'

[haxe]
format = 'via [$symbol]($style)'

[helm]
format = 'via [$symbol]($style)'

[java]
format = 'via [$symbol]($style)'

[julia]
format = 'via [$symbol]($style)'

[kotlin]
format = 'via [$symbol]($style)'

[lua]
format = 'via [$symbol]($style)'

[meson]
format = 'via [$symbol]($style)'

[mojo]
format = 'with [$symbol]($style)'

[nim]
format = 'via [$symbol]($style)'

[nodejs]
format = 'via [$symbol]($style)'

[ocaml]
format = 'via [$symbol(\($switch_indicator$switch_name\) )]($style)'

[odin]
format = 'via [$symbol]($style)'

[opa]
format = 'via [$symbol]($style)'

[perl]
format = 'via [$symbol]($style)'

[php]
format = 'via [$symbol]($style)'

[pixi]
format = 'via [$symbol($environment )]($style)'

[pulumi]
format = 'via [$symbol$stack]($style)'

[purescript]
format = 'via [$symbol]($style)'

[python]
format = 'via [$symbol]($style)'

[quarto]
format = 'via [$symbol]($style)'

[raku]
format = 'via [$symbol]($style)'

[red]
format = 'via [$symbol]($style)'

[rlang]
format = 'via [$symbol]($style)'

[ruby]
format = 'via [$symbol]($style)'

[rust]
format = 'via [$symbol]($style)'

[scala]
format = 'via [$symbol]($style)'

[solidity]
format = 'via [$symbol]($style)'

[swift]
format = 'via [$symbol]($style)'

[typst]
format = 'via [$symbol]($style)'

[vagrant]
format = 'via [$symbol]($style)'

[vlang]
format = 'via [$symbol]($style)'

[xmake]
format = "via [$symbol]($style)"

[zig]
format = 'via [$symbol]($style)'
